# -*- coding: utf-8 -*-
"""05_dbscan_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/adt-kmr/VoyageAI/blob/main/notebooks/05_dbscan_clustering.ipynb

# DBSCAN Clustering
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import silhouette_score
import time

# Load the dataset
X = pd.read_csv('../data/processed/finalclusteringdataset.csv')
start_time = time.time()

# Train–Test Split
from sklearn.model_selection import train_test_split
train_df, test_df = train_test_split(X, test_size=0.2, random_state=42)
X_train = train_df[['trip_frequency','average_booking_value','destination_diversity','session_duration','search_behavior']]
X_test = test_df[['trip_frequency','average_booking_value','destination_diversity','session_duration','search_behavior']]

# Find optimal epsilon using k-distance graph
neighbors = NearestNeighbors(n_neighbors=5)
neighbors_fit = neighbors.fit(X)
distances, indices = neighbors_fit.kneighbors(X)
distances = np.sort(distances[:, -1], axis=0)
# Plot k-distance graph
plt.figure(figsize=(10, 6))
plt.plot(distances)
plt.xlabel('Data Points sorted by distance')
plt.ylabel('5th Nearest Neighbor Distance')
plt.title('K-distance Graph for Epsilon Selection')
plt.grid(True)
plt.show()

# AUTOMATIC EPSILON SELECTION - using percentile method
eps_min = distances[int(len(distances)*0.95)]
eps_max = distances[int(len(distances)*0.99)]
eps_auto = (eps_min + eps_max) / 2  # Take midpoint

print(f'Suggested epsilon range: {eps_min:.4f} to {eps_max:.4f}')
print(f'Auto-selected epsilon: {eps_auto:.4f}')

# Apply DBSCAN with AUTO epsilon
min_samples = 5
dbscan = DBSCAN(eps=eps_auto, min_samples=min_samples, algorithm='auto')
cluster_labels = dbscan.fit_predict(X)
n_clusters = len(set(cluster_labels)) - (1 if -1 in cluster_labels else 0)
n_noise = list(cluster_labels).count(-1)

# Evaluate clustering (only if we have at least 2 clusters and not all noise)
if n_clusters > 1 and n_noise < len(X):
    mask = cluster_labels != -1
    if mask.sum() > 0:
        sample_idx = np.random.choice(mask.sum(), size=min(10000, mask.sum()), replace=False)
        sil_score = silhouette_score(X[mask].iloc[sample_idx], cluster_labels[mask][sample_idx])
    else:
        sil_score = None
else:
    sil_score = None

# Cluster Scatter Plot: Average_Booking_Value vs Trip_Frequency
plt.figure(figsize=(10, 7))
sns.scatterplot(data=X.assign(Cluster=cluster_labels),
                x='average_booking_value', y='trip_frequency',
                hue='Cluster', palette='viridis', s=50, alpha=0.7)
plt.title('DBSCAN Clustering: Average Booking Value vs Trip Frequency')
plt.xlabel('Average Booking Value')
plt.ylabel('Trip Frequency')
plt.legend(title='Cluster')
plt.grid(True, alpha=0.3)
plt.show()

# Visualize clusters (2D projection)
from sklearn.decomposition import PCA

# Reduce to 2D for visualization
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

plt.figure(figsize=(10, 7))
# Plot noise points separately
noise_mask = cluster_labels == -1
scatter = plt.scatter(X_pca[~noise_mask, 0], X_pca[~noise_mask, 1],
                      c=cluster_labels[~noise_mask], cmap='viridis', s=50, alpha=0.6)
plt.scatter(X_pca[noise_mask, 0], X_pca[noise_mask, 1],
           c='red', marker='x', s=100, label='Noise Points')

plt.xlabel(f'PC1 ({pca.explained_variance_ratio_[0]:.2%} variance)')
plt.ylabel(f'PC2 ({pca.explained_variance_ratio_[1]:.2%} variance)')
plt.title('DBSCAN Clustering Results')
plt.colorbar(scatter, label='Cluster')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

# Cluster distribution
unique, counts = np.unique(cluster_labels, return_counts=True)

plt.figure(figsize=(10, 5))
colors = ['red' if u == -1 else 'skyblue' for u in unique]
plt.bar(range(len(unique)), counts, color=colors, edgecolor='black')
plt.xlabel('Cluster')
plt.ylabel('Number of Data Points')
plt.title('DBSCAN Cluster Distribution')
plt.xticks(range(len(unique)), unique)
plt.grid(axis='y', alpha=0.3)
plt.show()

print('\nCluster Distribution:')
for cluster, count in zip(unique, counts):
    if cluster == -1:
        print(f'Noise Points: {count} samples ({count/len(X)*100:.2f}%)')
    else:
        print(f'Cluster {cluster}: {count} samples ({count/len(X)*100:.2f}%)')

# Calculate metrics before saving
end_time = time.time()
execution_time = end_time - start_time
# Print summary metrics
print(f'Number of Clusters: {n_clusters}')
if sil_score is not None:
    print(f'Silhouette Score: {sil_score:.4f}')
else:
    print('Silhouette Score: N/A')
for cluster, count in zip(unique, counts):
    if cluster == -1:
        print(f'Noise Points: {count} samples ({count/len(X)*100:.2f}%)')
    else:
        print(f'Cluster {cluster}: {count} samples ({count/len(X)*100:.2f}%)')
print(f'Execution Time: {execution_time:.2f} seconds')
# Save results
X['Cluster'] = cluster_labels
X.to_csv('../results/csv/dbscan_results.csv', index=False)

# Silhouette Score Comparison — Train vs Test
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

# Use the clusterer fitted on the full dataset to predict on train/test
train_labels = dbscan.fit_predict(X_train)
test_labels = dbscan.fit_predict(X_test)

# Remove noise points for silhouette calculation
train_mask = train_labels != -1
test_mask = test_labels != -1

train_score = silhouette_score(X_train[train_mask], train_labels[train_mask]) if train_mask.sum() > 1 else float('nan')
test_score = silhouette_score(X_test[test_mask], test_labels[test_mask]) if test_mask.sum() > 1 else float('nan')

scores = [train_score, test_score]
types = ['Train', 'Test']
plt.figure(figsize=(6,4))
bars = plt.bar(types, scores, color=['skyblue', 'salmon'])
plt.title('Silhouette Score Comparison — Train vs Test')
plt.ylabel('Silhouette Score')
for bar, score in zip(bars, scores):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height(), f'{score:.2f}', ha='center', va='bottom')
plt.show()
