# -*- coding: utf-8 -*-
"""06_hierarchical_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/adt-kmr/VoyageAI/blob/main/notebooks/06_hierarchical_clustering.ipynb

# Hierarchical Clustering
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster
from sklearn.metrics import silhouette_score, davies_bouldin_score
from sklearn.decomposition import PCA
import time








# Load dataset
X = pd.read_csv('../data/processed/finalclusteringdataset.csv')
start_time = time.time()

# Train–Test Split
from sklearn.model_selection import train_test_split
train_df, test_df = train_test_split(X, test_size=0.2, random_state=42)
X_train = train_df[['trip_frequency','average_booking_value','destination_diversity','session_duration','search_behavior']]
X_test = test_df[['trip_frequency','average_booking_value','destination_diversity','session_duration','search_behavior']]

print('\n Testing Different Linkage Methods')
linkage_methods = ['ward', 'complete', 'average', 'single']
best_linkage = None
best_sil_linkage = -1

# Sample for faster testing (use 20k samples)
sample_size = min(20000, len(X))
X_sample = X.sample(n=sample_size, random_state=42)

for method in linkage_methods:
    print(f'Testing {method}...')
    try:
        # Create linkage matrix with this method
        linkage_mat_temp = linkage(X_sample, method=method)

        # Test with k=3 clusters (temporary)
        temp_labels = fcluster(linkage_mat_temp, 3, criterion='maxclust')

        # Calculate silhouette on sample
        sil = silhouette_score(X_sample, temp_labels)
        print(f'  {method.capitalize()}: Silhouette = {sil:.4f}')

        if sil > best_sil_linkage:
            best_sil_linkage = sil
            best_linkage = method
    except Exception as e:
        print(f'  {method.capitalize()}: Failed - {e}')

print(f'\nAuto-selected linkage: {best_linkage} (Silhouette: {best_sil_linkage:.4f})')

#  Create Linkage Matrix with BEST METHOD
print(f'\n Computing linkage matrix using {best_linkage} method ')
# Use smaller sample for speed
use_full = len(X) <= 20000
if use_full:
    X_for_linkage = X
    print('Using full dataset for linkage')
else:
    X_for_linkage = X.sample(n=20000, random_state=42)
    print('Using 20k sample for linkage (faster)')

linkage_matrix = linkage(X_for_linkage, method=best_linkage)
print('Linkage matrix computed')

#  Plot Dendrogram
plt.figure(figsize=(15, 7))
dendrogram(linkage_matrix, truncate_mode='lastp', p=30,
           leaf_rotation=90, leaf_font_size=10, show_contracted=True)
plt.title(f'Hierarchical Clustering Dendrogram (Linkage: {best_linkage})')
plt.xlabel('Sample Index or (Cluster Size)')
plt.ylabel('Distance')
plt.grid(True, alpha=0.3)
plt.show()

#Auto-select OPTIMAL K
print('\nFinding Optimal Number of Clusters ===')
k_range = range(2, 11)
silhouette_scores = []
sample_for_eval = min(10000, len(X))

for k in k_range:
    print(f'Testing k={k}', end=' ')
    # Get cluster labels for this k
    cluster_labels_temp = fcluster(linkage_matrix, k, criterion='maxclust')

    # If we used a sample for linkage, we need to predict for all data
    if not use_full:
        # For the sample we used
        labels_sample = cluster_labels_temp
        eval_indices = np.random.choice(len(X_for_linkage),
                                       size=min(sample_for_eval, len(X_for_linkage)),
                                       replace=False)
        sil = silhouette_score(X_for_linkage.iloc[eval_indices],
                              labels_sample[eval_indices])
    else:
        # Sample for silhouette calculation from full data
        eval_indices = np.random.choice(len(X), size=sample_for_eval, replace=False)
        sil = silhouette_score(X.iloc[eval_indices],
                              cluster_labels_temp[eval_indices])

    silhouette_scores.append(sil)
    print(f'Silhouette = {sil:.4f}')

# Auto-select best k
best_k = k_range[np.argmax(silhouette_scores)]
best_score = max(silhouette_scores)
print(f'\nOptimal k: {best_k} (Silhouette: {best_score:.4f})')

# Plot silhouette scores
plt.figure(figsize=(10, 6))
plt.plot(k_range, silhouette_scores, 'bo-', linewidth=2, markersize=8)
plt.axvline(x=best_k, color='red', linestyle='--', linewidth=2,
            label=f'Optimal k={best_k}')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Silhouette Score')
plt.title('Optimal Number of Clusters')
plt.grid(True, alpha=0.3)
plt.legend()
plt.show()

# Apply Clustering (50k sample + KNN for rest)
print('\nApplying Final Clustering ')

if use_full:
    # Already have full linkage
    cluster_labels_sample = fcluster(linkage_matrix, best_k, criterion='maxclust')
    cluster_labels = cluster_labels_sample
else:
    # Cluster the 50k sample
    cluster_labels_sample = fcluster(linkage_matrix, best_k, criterion='maxclust')

    # Use KNN to assign remaining 50k points
    print('Assigning remaining points using KNN...')
    from sklearn.neighbors import NearestNeighbors

    sample_indices = X_for_linkage.index
    remaining_indices = X.index.difference(sample_indices)
    X_remaining = X.loc[remaining_indices]

    # KNN assignment
    knn = NearestNeighbors(n_neighbors=5)
    knn.fit(X_for_linkage)
    distances, indices = knn.kneighbors(X_remaining)

    # Majority vote from 5 nearest neighbors
    remaining_labels = []
    for i in range(len(X_remaining)):
        neighbor_clusters = cluster_labels_sample[indices[i]]
        most_common = np.bincount(neighbor_clusters).argmax()
        remaining_labels.append(most_common)

    # Combine all labels
    cluster_labels = np.zeros(len(X), dtype=int)
    cluster_labels[sample_indices] = cluster_labels_sample
    cluster_labels[remaining_indices] = remaining_labels
    print('All 100k points assigned')

# Visualize clusters (2D projection)
from sklearn.decomposition import PCA

# Reduce to 2D for visualization
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

plt.figure(figsize=(10, 7))
scatter = plt.scatter(X_pca[:, 0], X_pca[:, 1], c=cluster_labels, cmap='viridis', s=50, alpha=0.6)
plt.xlabel(f'PC1 ({pca.explained_variance_ratio_[0]:.2%} variance)')
plt.ylabel(f'PC2 ({pca.explained_variance_ratio_[1]:.2%} variance)')
plt.title('Hierarchical Clustering Results')
plt.colorbar(scatter, label='Cluster')
plt.grid(True, alpha=0.3)
plt.show()

# Cluster distribution
unique, counts = np.unique(cluster_labels, return_counts=True)
plt.figure(figsize=(10, 5))
plt.bar(unique, counts, color='skyblue', edgecolor='black')
plt.xlabel('Cluster')
plt.ylabel('Number of Data Points')
plt.title('Hierarchical Clustering Distribution')
plt.xticks(unique)
plt.grid(axis='y', alpha=0.3)
plt.show()

print('\nCluster Distribution:')
for cluster, count in zip(unique, counts):
    print(f'Cluster {cluster}: {count} samples ({count/len(X)*100:.2f}%)')

#  Evaluate Final Model
print('\nFinal Model Evaluation ')
sample_idx = np.random.choice(len(X), size=min(10000, len(X)), replace=False)
num_clusters = len(np.unique(cluster_labels))
if num_clusters < 2:
    print(f'Warning: Only {num_clusters} cluster(s) found. Cannot compute silhouette or Davies-Bouldin scores.')
    final_sil = None
    final_db = None
else:
    final_sil = silhouette_score(X.iloc[sample_idx], cluster_labels[sample_idx])
    final_db = davies_bouldin_score(X, cluster_labels)

print(f'Number of clusters: {best_k}')
print(f'Linkage method: {best_linkage}')
if final_sil is not None:
    print(f'Silhouette Score: {final_sil:.4f}')
else:
    print('Silhouette Score: N/A')

# Cluster Scatter Plot: Average_Booking_Value vs Trip_Frequency
import seaborn as sns
plt.figure(figsize=(10, 7))
sns.scatterplot(data=X.assign(Cluster=cluster_labels),
                x='average_booking_value', y='trip_frequency',
                hue='Cluster', palette='viridis', s=50, alpha=0.7)
plt.title('Hierarchical Clustering: Average Booking Value vs Trip Frequency')
plt.xlabel('Average Booking Value')
plt.ylabel('Trip Frequency')
plt.legend(title='Cluster')
plt.grid(True, alpha=0.3)
plt.show()






# Cluster Distribution
unique, counts = np.unique(cluster_labels, return_counts=True)

#  Save Results
end_time = time.time()
execution_time = end_time - start_time
n_clusters = len(unique)
sample_idx = np.random.choice(len(X), size=min(10000, len(X)), replace=False)
if n_clusters < 2:
    sil_score = None
else:
    sil_score = silhouette_score(X.iloc[sample_idx], cluster_labels[sample_idx])
# Print summary metrics
print(f'Number of Clusters: {n_clusters}')
if sil_score is not None:
    print(f'Silhouette Score: {sil_score:.4f}')
else:
    print('Silhouette Score: N/A')
for cluster, count in zip(unique, counts):
    print(f'Cluster {cluster}: {count} samples ({count/len(X)*100:.2f}%)')
print(f'Execution Time: {execution_time:.2f} seconds')
X['Cluster'] = cluster_labels
X.to_csv('../results/csv/hierarchical_results.csv', index=False)

print('HIERARCHICAL CLUSTERING FINAL SUMMARY')
print(f'Linkage Method (Auto-selected): {best_linkage}')
print(f'Optimal Clusters (Auto-selected): {best_k}')
print(f'Silhouette Score: {final_sil:.4f}')

# Silhouette Score Comparison - Train vs Test
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

SAMPLE_SIZE = 5000

# Train sample
train_idx = np.random.choice(len(X_train), size=min(SAMPLE_SIZE, len(X_train)), replace=False)
X_train_sample = X_train.iloc[train_idx]

# Test sample
test_idx = np.random.choice(len(X_test), size=min(SAMPLE_SIZE, len(X_test)), replace=False)
X_test_sample = X_test.iloc[test_idx]

# Linkage sirf sample pe compute karo
linkage_train = linkage(X_train_sample, method=best_linkage)
linkage_test = linkage(X_test_sample, method=best_linkage)

# Labels
train_labels_sample = fcluster(linkage_train, best_k, criterion='maxclust')
test_labels_sample = fcluster(linkage_test, best_k, criterion='maxclust')

# Silhouette scores
train_score = silhouette_score(X_train_sample, train_labels_sample)
test_score = silhouette_score(X_test_sample, test_labels_sample)

scores = [train_score, test_score]
types = ['Train', 'Test']

plt.figure(figsize=(6, 4))
bars = plt.bar(types, scores, color=['skyblue', 'salmon'])
plt.title('Silhouette Score Comparison - Train vs Test')
plt.ylabel('Silhouette Score')
for bar, score in zip(bars, scores):
    plt.text(bar.get_x() + bar.get_width()/2,
             bar.get_height()/2,
             f'{score:.2f}', ha='center', va='bottom')
plt.show()


