
"""04_kmeans_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/adt-kmr/VoyageAI/blob/main/notebooks/04_kmeans_clustering.ipynb

# K-Means Clustering
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import time  # Added for execution time tracking

