# -*- coding: utf-8 -*-
"""03_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/adt-kmr/VoyageAI/blob/main/notebooks/03_preprocessing.ipynb
"""

#preprocessing dataset in dataset.csv
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/dataset.csv')

print(df.shape)
print(df.head())

#identifying numeric columns
numericols=df.select_dtypes(include=np.number).columns.tolist()
print(numericols)

#identifying categorical columns
categoricalcols=df.select_dtypes(include=object).columns.tolist()
print(categoricalcols)

#handling missing values
# For Numeric Columns
for col in numericols:
    df[col] = df[col].fillna(df[col].mean())

# For Categorical Columns
for col in categoricalcols:
    df[col] = df[col].fillna(df[col].mode()[0])

#removing duplicate rows
df.drop_duplicates(inplace=True)

#outlier handling
for col in numericols:
    Q1=df[col].quantile(0.25)
    Q3=df[col].quantile(0.75)
    IQR=Q3-Q1
    lowerbound=Q1-1.5*IQR
    upperbound=Q3+1.5*IQR
    df[col]=np.where(df[col]<lowerbound,lowerbound,np.where(df[col]>upperbound,upperbound,df[col]))

# hot encoding of categorical variables
for col in categoricalcols:
    df[col]=df[col].astype('category')
    df[col]=df[col].cat.codes
    print(df.head())

#feature selection or column dropping
#dropping userid
df.drop('user_id',axis=1,inplace=True)

# Feature scaling and PCA demonstration
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Standard scaling
scaler = StandardScaler()
scaled_features = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_features, columns=df.columns)

# PCA for analysis only (do not use PCA columns in final output)
pca = PCA(n_components=None)
pca_features = pca.fit_transform(scaled_df)
explained_var = pca.explained_variance_ratio_

# Visualize explained variance ratio
plt.figure(figsize=(8,5))
plt.bar(range(1, len(explained_var)+1), explained_var, alpha=0.7)
plt.xlabel('Principal Component')
plt.ylabel('Explained Variance Ratio')
plt.title('Explained Variance Ratio by PCA Components')
plt.show()

# Retain only the 6 required columns for final clustering dataset
required_features = [
    'trip_frequency',
    'average_booking_value',
    'destination_diversity',
    'session_duration',
    'search_behavior',
]
final_df = scaled_df[required_features]
final_df.to_csv('finalclusteringdataset.csv', index=False)
print('Final clustering dataset saved successfully with only required features.')

required_columns = [
    'trip_frequency',
    'average_booking_value',
    'destination_diversity',
    'session_duration',
    'search_behavior'
]

final_df = df[required_columns]

print("Final dataset shape:", final_df.shape)
print("Final columns:", final_df.columns)

# Save final clustering dataset
final_df.to_csv("../data/processed/finalclusteringdataset.csv", index=False)

print("finalclusteringdataset.csv created successfully with only required columns.")

# Train–Test Split for Evaluation
from sklearn.model_selection import train_test_split
X_train, X_test = train_test_split(final_df, test_size=0.2, random_state=42)
print('Train–test split complete')
